import './globals.css'
import FavPng from "public/fav.png"
import {Analytics} from "@vercel/analytics/react";
import {Inter} from "next/font/google";
const inter = Inter ({
    weight: ["400", "500", "700", "900"],
    subsets: ["latin"]
});
export const metadata = {
    title: 'Typle | developer',
    description: 'Generated by next app',
    icons: [{rel: 'icon', url: FavPng.src}],
}


export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={`${inter.className} w-full bg-slate-900`} suppressHydrationWarning={true}>
            {children}
            <Analytics mode={'production'}/>
            </body>
        </html>
    )
}
